### ISSUE TITLE
Regarding zeroshot_weights.pth

### ISSUE THREAD

**Issue by jasonjeong3** [vobecant/POP3D#12]
Hi,

Thank you for your work on language driven occupancy prediction!
I had a question regarding the text embeddings used.
There only seem to be approximately 32 classes for nuScenes, however the embedding is of dimensions [102, 512] instead of [32, 512]. 
Would it be possible for you to provide text prompts used to generate the text embeddings?

Sincerely,
Jason

**Comment by vobecant** [comment]
Dear Jason,

thank you very much for your question. Please see Table 2 in our paper https://arxiv.org/abs/2401.09413 for the categories' descriptions.

Thanks,
Antonin.
