### ISSUE TITLE
Missing Visualization Code

### ISSUE THREAD

**Issue by NickHezhuolin** [vobecant/POP3D#13]
I was reviewing the repository and noticed that the visualization code for the project seems to be missing. Specifically, while trying to follow the provided scripts like TPVFormer, I encountered issues related to incomplete or missing visualization logic ( Miss ImagePoint_NuScenes_vis_wFeats ). It would be extremely helpful to have access to the full visualization code to better understand how to interpret the model outputs.

Would you be able to provide the full visualization implementation, or guide me on how to resolve the missing portions? It will greatly help in reproducing the results and properly visualizing the outputs from the model.

Thank you in advance for your support!

**Comment by vobecant** [comment]
Hi @NickHezhuolin, can you please check this and let me know if it works for you? https://github.com/vobecant/POP3D/blob/b0a86b2c4a3c443a0d2142776be819fbfa795488/visualization/dataset.py#L208

Thanks!

**Comment by vobecant** [comment]
I hope it works fine for you now! If you have any problems, please feel free to re-open the issue.
