### ISSUE TITLE
When debugging train.py with a single GPU, I see that 'text-embeddings-path' is missing. Where can I purchase it?

### ISSUE THREAD

**Issue by Gmonster-24** [vobecant/POP3D#14]
Wishes!

**Comment by vobecant** [comment]
Hey! Sorry for a late reply. It is probably a bit hidden in the instructions: https://github.com/vobecant/POP3D?tab=readme-ov-file#generate-maskclip-features
Here is the link: https://data.ciirc.cvut.cz/public/projects/2023POP3D/zeroshot_weights.pth
