### ISSUE TITLE
Why not evaluate it on ooc_gts, but on the lidar projection to the voxels

### ISSUE THREAD

**Issue by stickygao** [vobecant/POP3D#15]
Why not evaluate it on ooc_gts, but on the lidar projection to the voxels, what is the difference between this and the openscene of the point cloud. The OOC should be the output of a dense voxel result, not a sparse point cloud

**Comment by vobecant** [comment]
Hi, sorry I probably don't fully understand. Can you please try to rephrase it?

**Comment by stickygao** [comment]
I read in your article that “To evaluate our models on the task of 3D occupancy prediction, we need to convert
 the point-level semantic annotations from LiDAR to voxel-level annotations” However, 3D occupancy prediction has its own benchmark: https://github.com/Tsinghua-MARS-Lab/Occ3D, which is much denser than projecting point clouds into voxel space.

**Comment by vobecant** [comment]
Dear @stickygao , thank you very much for your comment. The dataset you refer to was published at the very same conference (NeurIPS'23) as our paper and therefore the data were not available at the time of the submission.

**Comment by stickygao** [comment]
Thanks for your reply
