### ISSUE TITLE
Can't download maskclip_plus_vit16_deeplabv2_r101-d8_512x512_8k_coco-stuff164k.pth

### ISSUE THREAD

**Issue by RikkiXu** [vobecant/POP3D#2]
Hi, thanks for posting the code! 
I'm having trouble reproducing the code. I can't download maskclip_plus_vit16_deeplabv2_r101-d8_512x512_8k_coco-stuff164k.pth, the page say I can't be found in the entuedu-my.sharepoint.com directory. Can you share it? Thanks

**Comment by vobecant** [comment]
Hi, can you please try this: https://entuedu-my.sharepoint.com/:u:/g/personal/chong033_e_ntu_edu_sg/EZSrnPaNFwNNqpECYCkgpg4BEjN782MUD7ZUEPXFWSTEXA?e=mOaseS ? 
If it does not work for you, please go to https://github.com/chongzhou96/MaskCLIP/tree/master/configs/maskclip_plus and download `COCO-Stuff 164k MaskCLIP+ ViT-B/16 DeepLabv2-R-101-d8 512x512`

**Comment by RikkiXu** [comment]
Thank you. I get it !
