### ISSUE TITLE
 Some files missing

### ISSUE THREAD

**Issue by RikkiXu** [vobecant/POP3D#3]
Hello, thanks for the code. 
I'm having some issues with reproduction. Some files seem to be missing in the builder folder like tpv_lidarseg_builder, tpv_occupancy_builder, loss_builder, etc.
load_save_util and prompt_extractor, etc are missing in the utils folder.
/_base_/optimizer.py is missing in the config folder, visualization folder is also missing.
Can you add to them, thank you very much!

**Comment by vobecant** [comment]
Hi, I've just added the builders. Sorry for the trouble.
If it still does not work, please feel free to re-open this issue.
