### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by bqm1111** [vobecant/POP3D#5]
Hi. Thank you for your code.

I have a problem while running the following command for evaluation
```
 python3 eval_maskclip.py --py-config config/pop3d_maskclip_12ep.py --resume-from ./pretrained/pop3d_weights.pth --maskclip --no-wandb --text-embeddings-path ./pretrained/zeroshot_weights.pth
```
It seems that load_save_util and prompt_extractor, etc are missing in the utils folder.
/base/optimizer.py is missing in the config folder, visualization folder is also missing.

Could you please upload those files? Thank you very much

**Comment by vobecant** [comment]
Hi, I uploaded the missing files, sorry for the problems. Can you please try it now?

**Comment by bqm1111** [comment]
Some files are still missing. I had the following message
```
ModuleNotFoundError: No module named 'utils.lovasz_losses'
```
I think you borrowed this code from TPVFormer then I added lovasz_losses.py to utils folder. However, I ran into another error
```
ModuleNotFoundError: No module named 'dataloader.transform_3d'
```
Could you please add all necessary file to run it successfully?

**Comment by bqm1111** [comment]
prompt_extractor.py is still missing in utils folder. optimizer.py is also missing in config/_base_ folder

**Comment by vobecant** [comment]
It should be fixed now.

**Comment by bqm1111** [comment]
When I run
```
python tools/extract_features.py ${CFG_PATH} --save-dir ${OUT_DIR} --checkpoint ${CKPT_PATH} --projections-dir ${PROJ_DIR} --complete
```
The following error occured
```
Path to the text embeddings given but the file does not exist! Path: pretrain/nuscenes_ViT16_clip_text.pth
```
Could you tell me how to generate file nuscenes_ViT16_clip_text.pth?

**Comment by bqm1111** [comment]
Also, there is an issue in term of model checkpoint. I got the following error
```
size mismatch for decode_head.text_embeddings: copying a param with shape torch.Size([171, 512]) from checkpoint, the shape in current model is torch.Size([28, 512]).
```
Could you tell me how to fix this?

**Comment by vobecant** [comment]
> Could you tell me how to generate file nuscenes_ViT16_clip_text.pth?

Did you run the step 1) here? https://github.com/vobecant/POP3D?tab=readme-ov-file#generate-maskclip-features 

```mkdir -p ./pretrain
python tools/maskclip_utils/convert_clip_weights.py --model ViT16 --backbone
python tools/maskclip_utils/convert_clip_weights.py --model ViT16
```

**Comment by vobecant** [comment]
> Could you tell me how to fix this?

It doesn't matter, we don't use it.

**Comment by bqm1111** [comment]
> > Could you tell me how to generate file nuscenes_ViT16_clip_text.pth?
> 
> Did you run the step 1) here? https://github.com/vobecant/POP3D?tab=readme-ov-file#generate-maskclip-features
> 
> ```
> python tools/maskclip_utils/convert_clip_weights.py --model ViT16 --backbone
> python tools/maskclip_utils/convert_clip_weights.py --model ViT16
> ```

I ran it already and it only created 2 files named "ViT16_clip_backbone.pth" and "ViT16_clip_weights.pth". Not sure if they are the same as "nuscenes_ViT16_clip_text.pth"

**Comment by vobecant** [comment]
> I ran it already and it only created 2 files named "ViT16_clip_backbone.pth" and "ViT16_clip_weights.pth". Not sure if they are the same as "nuscenes_ViT16_clip_text.pth"

You get this problem only if you try to generate the features with MaskCLIP? If so, you don't need to be bothered, as these weights are not used during feature extraction.

**Comment by bqm1111** [comment]
When I run

```
 python3 eval_maskclip.py --py-config config/pop3d_maskclip_12ep.py --resume-from ./pretrained/pop3d_weights.pth --maskclip --no-wandb --text-embeddings-path ./pretrained/zeroshot_weights.pth
```
I got the following error
```
Namespace(py_config='config/pop3d_maskclip_12ep.py', work_dir='./out/tpv_lidarseg_26122023_124916', resume_from='./pretrained/pop3d_weights.pth', name='tpv_lidarseg_26122023_124916', eval_at_start=False, no_dist=False, compute_weights=False, compute_upperbound_clip=False, debug=False, agnostic=False, class_weights_path=None, no_wandb=True, ft_loss_weight=1.0, maskclip=True, show=False, text_embeddings_path='./pretrained/zeroshot_weights.pth', max_iter=None, projected_features=False, plot_dir=None, dec_layers_occupancy=None, dec_layers_features=None, hidden_dims=512, hidden_dims_ft=1024, num_classes=None, normalized_cosine=False, val_on_train=False, gpus=1)
socket.gethostname(): sherlock
Initial port: 20506
tcp://127.0.0.1:20506
Traceback (most recent call last):
  File "/home/sherlock/workspace/POP3D/eval_maskclip.py", line 783, in <module>
    torch.multiprocessing.spawn(main, args=(args,), nprocs=args.gpus)
  File "/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/sherlock/workspace/POP3D/eval_maskclip.py", line 210, in main
    cfg.dump(osp.join(args.work_dir, osp.basename(args.py_config)))
  File "/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/site-packages/mmcv/utils/config.py", line 564, in dump
    f.write(self.pretty_text)
  File "/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/site-packages/mmcv/utils/config.py", line 502, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
TypeError: FormatCode() got an unexpected keyword argument 'verify'
```
Could you tell me what is the problem here?

**Comment by vobecant** [comment]
> Could you tell me what is the problem here?

It looks like a `yapf` issue. I found this solution: https://github.com/open-mmlab/mmdetection/issues/10962

**Comment by bqm1111** [comment]
I used that solution and the error disappear. However, other errors arise. Here is the message

```
<All keys matched successfully> (local_rank 0)
successfully resumed from epoch 12 (local_rank 0)
Start training! (local_rank 0)
len(used_dataloader): 6019
Traceback (most recent call last):
  File "/home/sherlock/workspace/POP3D/eval_maskclip.py", line 783, in <module>
    torch.multiprocessing.spawn(main, args=(args,), nprocs=args.gpus)
  File "/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 130, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL

  File "<string>", line 1, in <module>
  File "/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
/home/sherlock/anaconda3/envs/maskclip/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 11 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by bqm1111** [comment]
By the way, currently I only want to evaluate your method, not to train. Could you please provide a simple demo without running the whole nuscenes dataset like you currently have?

**Comment by vobecant** [comment]
> I used that solution and the error disappear. However, other errors arise. Here is the message

This seems to be pytorch-related issue. I would recommend to debug with using 0 workers in the dataloader.

**Comment by vobecant** [comment]
> By the way, currently I only want to evaluate your method, not to train. Could you please provide a simple demo without running the whole nuscenes dataset like you currently have?

You can now evaluate just the `mini` version of the validation set by using
```
CFG="config/pop3d_maskclip_12ep_mini.py"
```

**Comment by bqm1111** [comment]
It seems that the mini version that you are talking about is a subset of the whole trainval set. In order to run it, I still have to download the whole dataset (10 subfolders) which my laptop does not have enough storage for it. Could you please provide the code to generate the *_info_file.pkl file that you used in your dataloader so that I can experiment with the v1.0-mini dataset of nuscenes? This way I dont have to download the whole dataset to experiment your method.
