### ISSUE TITLE
About inference and training

### ISSUE THREAD

**Issue by ttomtom6** [vobecant/POP3D#6]
Thanks for your great work! It really helps me a lot.
When I run `eval.py`, only the  `val_miou_vox_agn` can be obtained withou the `val_miou_vox_clip_all` in the instruction.  Is there something wrong here?
Additionally, there seems to be a missing part (text embedding model) in the training code. Can this part be uploaded as well?

**Comment by vobecant** [comment]
Hi, sorry for this, I added `val_miou_vox_clip_all` to print.
Also, what do you mean by "text embedding model"?

**Comment by ttomtom6** [comment]
Thanks your reply! Yes, I want to retrain this excellent model on other datasets but this model is missing. It would be great if the whole training pipeline is provided.

**Comment by vobecant** [comment]
If I understand it correctly, you want to know how to generate the text embeddings for the classes you want to evaluate. 
We have an example of how do we generate these embeddings for nuScenes in `MaskCLIP/tools/maskclip_utils/prompt_engineering.py`. If you want to use a different set of classes, you need to define such set and generate these embeddings using this script.

**Comment by ttomtom6** [comment]
Thanks your reply!

**Comment by RikkiXu** [comment]
Hi, I encountered an error when running eval.py. The error location is as follows:
[        grid_ind_float_features = self.voxelization(xyz[matching_points])](https://github.com/vobecant/POP3D/blob/95abd09f7011916902bcea6b828864721a5fb0ae/dataloader/dataset_wrapper.py#L198)
*** IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
My matching_points is a list of length 6, xyz is an array of size (34720, 3)
Please tell me how to fix it.
@vobecant @ttomtom6

**Comment by vobecant** [comment]
Hi @RikkiXu , thank you for your interest in our code. I am sorry, but I don't know how to help you as the code works fine on my side. @ttomtom6 , did you encounter any problems like this? Thanks!

**Comment by ttomtom6** [comment]
Hi @RikkiXu , I am sorry that I haven't encountered this issue. Perhaps you need to check your environment.

**Comment by vobecant** [comment]
Dear @RikkiXu, since @ttomtom6 did not encounter the same issue as you did, I think that the problem is really in your environment.
